### ISSUE TITLE
publish ipa to artifactory?

### ISSUE THREAD

**Issue by cthai** [apphance/Apphance-MobilE-Build-Automation#1]
Hi, this is a great plugin addition to gradle. thanks.

I use artifactory to maintain all my artifacts for deployment.  can you shed some light on how to do this with this plugin and gradle to artifactory?

thanks,
cthai

**Comment by potiuk** [comment]
Hello. We plan to do it soon - we should declare outputs from our plugins properly. 

But I think you could use it even before. Simply declare artifacts in your gradle build and use built-in gradle's publishing functionality.

More on this you can find here: http://gradle.org/docs/current/userguide/artifact_management.html
