### ISSUE TITLE
Cannot get property 'value' on null object

### ISSUE THREAD

**Issue by pouljohn1** [apphance/Apphance-MobilE-Build-Automation#14]
When building framework project, apphance flow tries to get version code from project plist. Problem is that framework may not have plist. In addition AbstractIOSVariant.groovy:getPlist() method use LAUNCH_ACTION instead of BUILD_ACTION for framework.

When releasing this project everything works fine - in this situation we get version code from jenkins version.

**Comment by sawicki-maciej** [comment]
I tried adding simple bash script before gradle build step:
[ -z "$VERSION_CODE" ] && export VERSION_CODE=$BUILD_NUMBER

it didn't helped :(

**Comment by Opalo** [comment]
This is not an issue :) It's well known that there's no version code nor plist for framework variant. This what You need to do is to provide fake version code, as well as fake version string in build.gradle for instance.
