### ISSUE TITLE
git.branch property in gradle.properties never used

### ISSUE THREAD

**Issue by ghost** [apphance/Apphance-MobilE-Build-Automation#3]
File gradle.properties has been generated by prepareSetup task.

The file contains git.branch property set by the user.
It seems that the property is never used in the code:

File: GitPlugin.groovy
lines: 47-104

**Comment by wojtekerbetowski** [comment]
Thanks for submitting!

**Comment by potiuk** [comment]
Same: this task is gone now. We do not need VCS integration any more.
