### ISSUE TITLE
Can't execute saveReleaseInfoInVCS task

### ISSUE THREAD

**Issue by ghost** [apphance/Apphance-MobilE-Build-Automation#4]
Steps to reproduce the problem:
1. enable ameba-git-plugin
2. configure git.branch property in gradle.properties
3. execute 'saveReleaseInfoInVCS'

Result:

The execution failed for task ':saveReleaseInfoInVCS'.

> Error when executing git commit -m "Incrementing application version to NOVERSION (0)" AndroidManifest.xml :
>      working directory: /home/maciek/test-ameba/android-test,

```
 exit value: 1,

 errorOutput:

      ,
```

Expected result: 
The task gets executed

**Comment by potiuk** [comment]
This task is gone in latest version of Ameba. We got rid of the VCS integration, instead we are using Jenkins build numbers (passing them to updateVersion task). BTW. 1.0 version of Ameba is coming soon.
