### ISSUE TITLE
add copy ota task

### ISSUE THREAD

**Issue by sawicki-maciej** [apphance/Apphance-MobilE-Build-Automation#7]
Ameba should be able to copy ota artefacts to given dir (specified in gradle.properties or env variable).

This will allow to use nfs (and other file sharing protocols i.e. smb) to copy ota to http server (usually different machine) with out using jenkins scp copy plugin.

The problem with jenkins scp plugin is that it can not be run before ameba. Ameba sends release emails, and sometimes user get release email before ota files are copied. Adding this functionality will allow to control if files ware copied and send release email only when file copping succeeded.

**Comment by potiuk** [comment]
This should be done at the level of jenkins.
